services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lotus
      POSTGRES_PASSWORD: lotus
      POSTGRES_DB: lotus

  backend:
    env_file:
      - ./env/.env.prod
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: build
    expose:
      - 8000
    volumes:
      - django_static_volume:/lotus/staticfiles
    command: >
      sh -c "python3 manage.py wait_for_db && \
              python3 manage.py migrate && \
              python3 manage.py initadmin && \
              python3 manage.py setup_tasks && \
              python3 manage.py collectstatic --no-input && \
              gunicorn lotus.wsgi:application -w 4 --threads 4 -b :8000 --reload"
    depends_on:
      - db

  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: production
    stdin_open: true
    ports:
      - 80:80
    volumes:
      - django_static_volume:/app/backend/server/django_staticfiles
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server
    env_file:
      - ./env/.env.prod

  celery:
    env_file:
      - ./env/.env.prod
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: build
    command: celery -A lotus worker -l info
    depends_on:
      - redis
      - backend

  celery-beat:
    env_file:
      - ./env/.env.prod
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: build
    command: celery -A lotus beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celery
      - backend
      - redis

volumes:
  pgdata:
  django_static_volume:
