services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./pgdata_dev:/var/lib/postgresql/data
    env_file:
      - ./env/.env.dev

  backend:
    env_file:
      - ./env/.env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./backend/lotus:/lotus/lotus
      - ./backend/metering_billing:/lotus/metering_billing
    command: sh -c "./scripts/start_backend.dev.sh"
    depends_on:
      - db
      - redis

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    command: yarn run dev --host 0.0.0.0 --port 3000
    volumes:
      - ./frontend/src:/frontend/src:delegated
      - ./frontend/public:/frontend/public:delegated
      - /frontend/node_modules/
    stdin_open: true
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server
    env_file:
      - ./env/.env.dev

  celery:
    env_file:
      - ./env/.env.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    command: celery -A lotus worker -l info
    depends_on:
      - redis
      - backend
    restart: on-failure

  celery-beat:
    env_file:
      - ./env/.env.dev
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    command: celery -A lotus beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celery
      - backend
      - redis

volumes:
  pgdata_dev:
