
services:

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}

  lotus:
    container_name: lotus_django
    env_file:
      - ./env/.env
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./lotus:/lotus
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate_schemas &&
             python manage.py collectstatic --no-input &&
             python3 manage.py initadmin &&
             python3 manage.py runserver 0.0.0.0:8000
             "
    depends_on:
      - db
  redis:
    image: redis:7-alpine
    command: redis-server
    env_file:
      - ./env/.env

  celery:
    env_file:
     - ./env/.env
    build:
      context: .
    command: celery -A lotus worker -l info
    volumes:
      - ./lotus:/lotus
    depends_on:
      - db
      - redis
      - lotus
  celery-beat:
    env_file:
      - ./env/.env
    build:
      context: .
    command: celery -A lotus beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./lotus:/lotus
    depends_on:
      - redis
      - db
volumes:
  pgdata:
