services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    env_file:
      - ./env/.env
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    env_file:
      - ./env/.env
    build:
      context: ./lotus
      dockerfile: Dockerfile
      target: build
    expose:
      - 8000
    volumes:
      - django_static_volume:/code/staticfiles
    command: >
      sh -c "python3 manage.py wait_for_db && \
              python3 manage.py migrate && \
              python3 manage.py initadmin && \
              python3 manage.py setup_tasks && \
              python3 manage.py collectstatic --no-input && \
              gunicorn lotus.wsgi:application -w 4 --threads 4 -b :8000 --reload"
    depends_on:
      - db

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - 80:80
    volumes:
      - django_static_volume:/app/backend/server/django_staticfiles
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server
    env_file:
      - ./env/.env

  celery:
    env_file:
      - ./env/.env
    build:
      context: ./lotus
      dockerfile: Dockerfile
      target: build
    command: celery -A lotus worker -l info
    depends_on:
      - redis
      - backend

  celery-beat:
    env_file:
      - ./env/.env
    restart: on-failure
    build:
      context: ./lotus
      dockerfile: Dockerfile
      target: build
    command: celery -A lotus beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celery
      - backend

volumes:
  pgdata:
  django_static_volume:
