services:
  db:
    image: postgres:14-alpine
    restart: on-failure
    env_file:
      - ./env/.env.dev
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    env_file:
      - ./env/.env.dev
    build:
      context: ./lotus
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./lotus:/code
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    command: yarn run dev --host 0.0.0.0 --port 3000
    volumes:
      - ./frontend:/frontend:delegated
      - /frontend/node_modules/
    stdin_open: true
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server
    env_file:
      - ./env/.env.dev

  celery:
    env_file:
      - ./env/.env.dev
    build: ./lotus
    command: celery -A lotus worker -l info
    depends_on:
      - redis
      - backend

  celery-beat:
    env_file:
      - ./env/.env.dev
    restart: on-failure
    build: ./lotus
    command: celery -A lotus beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celery

volumes:
  pgdata:
