version: '3'

services:


  db:
    image: postgres:10-alpine
    restart: always
    env_file:
    - .env.dev

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
    - .env.dev
    depends_on:
      - db
  redis:
    image: redis:alpine
    command: redis-server

  celery:
    restart: always
    build:
      context: .
    command: celery -A lotus worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    build:
      context: .
    command: celery -A lotus beat -l info
    volumes:
      - ./app:/app
    environment:
      - ./.env.dev
    depends_on:
      - redis
      - db
volumes:
  pgdata:
