name: Lint and Prettier

on: [push]

jobs:
  format-ts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: frontend
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd frontend/frontend && yarn

      # - name: Lint with ESLint
      #   run: yarn lint
      - name: Run Prettier
        run: cd frontend/frontend && yarn pretty

  format-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install black

      - name: Run black
        run: black backend/
