"on":
  push:
    branches:
      - main
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Event Ingestion
        timeout-minutes: 20
        uses: porter-dev/porter-update-action@v0.1.0
        with:
          app: event-ingestion
          cluster: "2539"
          host: https://dashboard.getporter.dev
          namespace: default
          project: "5324"
          tag: ${{ steps.vars.outputs.sha_short }}
          token: ${{ secrets.PORTER_TOKEN_5324 }}

      - name: Event Guidance
        timeout-minutes: 20
        uses: porter-dev/porter-update-action@v0.1.0
        with:
          app: event-guidance
          cluster: "2539"
          host: https://dashboard.getporter.dev
          namespace: default
          project: "5324"
          tag: ${{ steps.vars.outputs.sha_short }}
          token: ${{ secrets.PORTER_TOKEN_5324 }}

      - name: Build Image
        timeout-minutes: 20
        uses: porter-dev/porter-cli-action@v0.1.0
        with:
          command: update build --app django-mono --tag ${{ steps.vars.outputs.sha_short }} --stream
        env:
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_CLUSTER: 2539
          PORTER_PROJECT: 5324
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_5324 }}

      - name: Push Image
        timeout-minutes: 20
        uses: porter-dev/porter-cli-action@v0.1.0
        with:
          command: update push --app django-mono --tag ${{ steps.vars.outputs.sha_short }} --stream
        env:
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_CLUSTER: 2539
          PORTER_PROJECT: 5324
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_5324 }}

      - name: Update Release Job
        timeout-minutes: 20
        uses: porter-dev/porter-cli-action@v0.1.0
        with:
          command: update config --app backend-release --tag ${{ steps.vars.outputs.sha_short }} --stream
        env:
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_CLUSTER: 2539
          PORTER_PROJECT: 5324
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_5324 }}

      # - name: Run Migration Job
      #   uses: porter-dev/porter-run-job-action@v0.1.0
      #   with:
      #     job: backend-release
      #     cluster: 2539
      #     project: 5324
      #     token: ${{ secrets.PORTER_TOKEN_5324 }}

      - name: Update Django Mono
        timeout-minutes: 20
        uses: porter-dev/porter-cli-action@v0.1.0
        with:
          command: update config --app django-mono --tag ${{ steps.vars.outputs.sha_short }} --stream
        env:
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_CLUSTER: 2539
          PORTER_PROJECT: 5324
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_5324 }}

      - name: Update Celery Worker
        timeout-minutes: 20
        uses: porter-dev/porter-cli-action@v0.1.0
        with:
          command: update config --app celery-worker --tag ${{ steps.vars.outputs.sha_short }} --stream
        env:
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_CLUSTER: 2539
          PORTER_PROJECT: 5324
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_5324 }}

      - name: Update Celery Beat
        timeout-minutes: 20
        uses: porter-dev/porter-cli-action@v0.1.0
        with:
          command: update config --app celery-beat --tag ${{ steps.vars.outputs.sha_short }} --stream
        env:
          PORTER_HOST: https://dashboard.getporter.dev
          PORTER_CLUSTER: 2539
          PORTER_PROJECT: 5324
          PORTER_TOKEN: ${{ secrets.PORTER_TOKEN_5324 }}
