"on":
  push:
    branches:
    - main
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Update Porter App
      timeout-minutes: 20
      uses: porter-dev/porter-update-action@v0.1.0
      with:
        app: event-ingestion
        cluster: "2539"
        host: https://dashboard.getporter.dev
        namespace: default
        project: "5324"
        tag: ${{ steps.vars.outputs.sha_short }}
        token: ${{ secrets.PORTER_TOKEN_5324 }}
